apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: auth
  ports:
  - port: 8083
    targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
  - port: 8083
    targetPort: 8083
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:8081/eureka/
        - name: DB_HOST
          value: 127.0.0.1:3306
        image: valdearados/clothing_store_franchise_authentication
        ports:
        - containerPort: 8083
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
        command: ["/cloud_sql_proxy",
            "-instances=divine-builder-276216:europe-west2:auth-db=tcp:3306",
            "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: cloudsql
        emptyDir: 
