apiVersion: v1
kind: Service
metadata:
  name: customers
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: customers
  ports:
  - port: 8085
    targetPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  type: ClusterIP
  selector:
    app: customers
  ports:
  - port: 8085
    targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
  labels:
    app: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
      - name: customers
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:8081/eureka/
        - name: DB_HOST
          value: 127.0.0.1:1433
        image: valdearados/clothing_store_franchise_customers
        ports:
        - containerPort: 8085
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
        command: ["/cloud_sql_proxy",
            "-instances=divine-builder-276216:europe-west2:customer-db=tcp:1433",
            "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: cloudsql
        emptyDir: