apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: eureka
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  type: ClusterIP
  selector:
    app: eureka
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:8081/eureka/
        name: eureka
        image: valdearados/clothing_store_franchise_discovery
        ports:
        - containerPort: 8081
            
