apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: gateway
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:8081/eureka/
        image: valdearados/clothing_store_franchise_gateway
        name: gateway
        ports:
        - containerPort: 8080