apiVersion: v1
kind: Service
metadata:
  name: inventory
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: inventory
  ports:
  - port: 8084
    targetPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
  - port: 8084
    targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:8081/eureka/
        - name: DB_HOST
          value: 127.0.0.1:3306
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        image: valdearados/clothing_store_franchise_inventory
        ports:
        - containerPort: 8084
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
        command: ["/cloud_sql_proxy",
            "-instances=divine-builder-276216:europe-west2:inventory-db=tcp:3306",
            "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: cloudsql
        emptyDir: